name: Build and Deploy to Development

on:
  push:
    branches: [main]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.sha }}
            ghcr.io/${{ github.repository }}:development
  deploy-docker-image:
    needs: build-docker-image
    runs-on: ubuntu-latest
    steps:
      - name: Initialize doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log into K8s cluster
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 zfw-k8s
      - name: Deploy image to cluster
        run: kubectl set image deployment/vatusa-sync-dev vatusa-sync-dev=ghcr.io/${{ github.repository }}:${{ github.sha }} --record -n zfw-staging-web-stack
      - name: Verify deployment
        run: kubectl rollout status deployment/vatusa-sync-dev -n zfw-staging-web-stack